title: Uncharted Systems # The title of the blog
#author: # Your name
email: Dan@Uncharted.Systems # your email shown in the footer
url: https://uncharted.systems # this is your site's root address.
# favicon: "./Curiosity.ico" # set the favicon of the site
